// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvA0u1oEfSpmxgTjqrdMrunaaNOfZNUoY',
    appId: '1:925106374810:web:a4dcdd96e42573b249b723',
    messagingSenderId: '925106374810',
    projectId: 'flutter-firebase-basics-5fb1d',
    authDomain: 'flutter-firebase-basics-5fb1d.firebaseapp.com',
    storageBucket: 'flutter-firebase-basics-5fb1d.appspot.com',
    measurementId: 'G-5SJQVK9WFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4KmNpty_pIHKdo_FZOs7jGHKjPrdh5E',
    appId: '1:925106374810:android:1f80709c357b94ec49b723',
    messagingSenderId: '925106374810',
    projectId: 'flutter-firebase-basics-5fb1d',
    storageBucket: 'flutter-firebase-basics-5fb1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdMq-JMDQFa8a1znc5V0CcXhrQ15atqg',
    appId: '1:925106374810:ios:9ae39194f9270f6b49b723',
    messagingSenderId: '925106374810',
    projectId: 'flutter-firebase-basics-5fb1d',
    storageBucket: 'flutter-firebase-basics-5fb1d.appspot.com',
    iosBundleId: 'com.example.project07',
  );
}
